name: ci_cd
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  table_calendar: ^3.1.2
  intl: ^0.19.0
  datetime_picker_formfield_new: ^2.1.0
  timelines_plus: ^1.0.3
  fl_chart: ^0.69.2
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  skeletonizer: ^1.4.2
  go_router: ^14.6.1
  collection: ^1.18.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  #flutter_phone_direct_caller: ^2.1.1
  #another_telephony: ^0.3.0
  #loading_animation_widget: ^1.3.0
  #flutter_secure_storage: ^9.2.2
  #flutter_native_splash: ^2.4.3
  #dio: ^5.7.0
  #cached_query_flutter: ^2.4.4
  #line_icons: ^2.0.3
  #firebase_core: ^3.8.0
  #firebase_messaging: ^15.1.5
  #flutter_local_notifications: ^18.0.1
  #package_info_plus: ^8.1.1
  #flutter_cached_pdfview: ^0.4.3
  #audioplayers: ^6.1.0
  #phone_state: ^2.0.1
  #flutter_typeahead: ^5.2.0
  #shared_preferences: ^2.3.3
  #connectivity_plus: ^6.1.0
  #animated_list_plus: ^0.5.2
  #pinput: ^5.0.0
  #smart_auth: ^2.0.0
  #rxdart: ^0.28.0
  #flutter_keyboard_visibility: ^6.0.0
  #timeago: ^3.7.0
  #path_provider: ^2.1.5
  #flutter_slidable: ^3.1.1
  #animated_tree_view: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
