name: Flutter CI/CD

on:
  push:
    branches:
      - dev
      - prod
      - qa

jobs:
  build-android:
    name: Build APK or App Bundle
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Flutter version
        run: flutter --version

      - name: Flutter doctor
        run: flutter doctor -v

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get
          flutter clean

      # Step 5: Set environment variables based on branch (diff apk or bundle)
      - name: Set branch-specific variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      # Step 6: Decode and configurate keystore and properties
      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # Step 7: Create Key properties
      - name: "Create Key properties"
        env:
          STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "storeFile=../app/upload-keystore.jks" >> android/key.properties
          echo "storePassword=${STORE_PASSWORD}" >> android/key.properties
          echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
          echo "keyAlias=${KEY_ALIAS}" >> android/key.properties

      # Step 8: Build the app
      - name: Build APK or App Bundle
        run: |
          flutter build apk --release --verbose \
          --dart-define=API_NSV_URL=${{vars.API_NSV_URL}} \
          --dart-define=API_SEGURIDAD_URL=${{ vars.API_SEGURIDAD_URL }} \
          --dart-define=LABEL_VERSION=${{ vars.LABEL_VERSION }}

      # Step 9: Verify Signature
      - name: Install Android SDK Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk-build-tools

      - name: Verify APK Signature (v2)
        run: |
          apksigner verify --verbose --print-certs build/app/outputs/flutter-apk/app-release.apk

      # Step 10: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-output
          overwrite: true
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
