name: Flutter CI/CD

on:
  push:
    branches:
      - dev
      - prod
      - qa
  pull_request:
    branches:
      - dev

jobs:
  build-android:
    name: Build APK or App Bundle
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - run: flutter --version
        name: show update workflow en el mismo push

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Set environment variables based on branch
      - name: Set branch-specific variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      # 4. Decodificar y configurar el keystore
      - name: Decode keystore
        run: |
          echo ${{secrets.ANDROID_KEYSTORE_BASE64}} | base64 -d > android/app/upload-keystore.jks

      #Create Key properties
      - name: "Create Key properties"
        env:
          STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: /
          pwd
          echo "storeFile" >> "android/app/upload-keystore.jks" >> android/key.properties
          echo "storePassword=${STORE_PASSWORD}" >> android/key.properties
          echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
          echo "keyAlias=${KEY_ALIAS}" >> android/key.properties

      # Step 6: Build the app
      - name: Build APK or App Bundle
        run: flutter build apk --release --dart-define=API_NSV_URL=${{vars.API_NSV_URL}}

      # Step 7: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-output
          overwrite: true
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
