name: Flutter CI/CD

on:
  push:
    branches:
      - dev
      - prod
      - qa
  pull_request:
    branches:
      - dev

jobs:
  build-android:
    name: Build APK or App Bundle
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - run: flutter --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Set environment variables based on branch
      - name: Set branch-specific variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      # Step 6: Build the app
      - name: Build APK or App Bundle
        run: flutter build apk --release --dart-define=API_BASE_URL=https://dev.api.com --dart-define=ENVIRONMENT=development

      # Step 7: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-output
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
